#finance-datareader로 지수 불러오기

In [ ]:
'''
한국 주요 지수            미국 주요 지수                              국가별 대표 지수

심볼	설명                심볼	설명                                  심볼	설명
KS11	KOSPI 지수          DJI	다우존스 지수                           JP225	닛케이 225 선물
KQ11	KOSDAQ 지수         IXIC	나스닥 종합 지수                      STOXX50	유럽 STOXX 50
KS50	KOSPI 50 지수       US500	S&P 500 지수                          HK50	항셍 지수
KS100	KOSPI 100           RUTNU	러셀 2000 (US Small Cap 2000)         CSI300	CSI 300 (중국)
KRX100	KRX 100           VIX	CBOE 변동성 지수 (공포지수)             TWII	대만 가권 지수
KS200	코스피 200                                                      HNX30	베트남 하노이
                                                                      SSEC	상해 종합
                                                                      UK100	영국 FTSE
                                                                      DE30	독일 DAX 30
                                                                      FCHI	프랑스 CAC 40
'''

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
cd "/content/drive/MyDrive/Colab Notebooks/project-rl"
!dir

In [ ]:
!pip install finance-datareader
import FinanceDataReader as fdr

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting finance-datareader
  Downloading finance_datareader-0.9.42-py3-none-any.whl (17 kB)
Requirement already satisfied: pandas>=0.19.2 in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (1.3.5)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (2.23.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (4.9.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from finance-datareader) (4.64.1)
Collecting requests-file
  Downloading requests_file-1.5.1-py2.py3-none-any.whl (3.7 kB)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->finance-datareader) (2022.4)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->finance-datareader) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->finance-datareader) (1.21.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.19.2->finance-datareader) (1.15.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->finance-datareader) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->finance-datareader) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->finance-datareader) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->finance-datareader) (2022.9.24)
Installing collected packages: requests-file, finance-datareader
Successfully installed finance-datareader-0.9.42 requests-file-1.5.1

In [ ]:
# ks11 = fdr.DataReader('KS11', '2015-01-01')  #(지수, 시작날짜, 끝날짜)
# dji = fdr.DataReader('DJI' ) # Dow Jones Industrial(DJI)
# sp = fdr.DataReader('US500') # S&P 500 지수 (NYSE)
# csi = fdr.DataReader('CSI300')  # CSI300 지수
jp = fdr.DataReader('JP225')  # 닛케이 225 선물 지수

In [ ]:
print(len(ks11), len(dji), len(sp), len(csi), len(jp))

1920 10797 10798 4327 5366

In [ ]:
jp

               Close      Open      High       Low       Volume  Change
Date
2001-01-05  13867.61  13763.22  13947.06  13725.46          0.0  0.0129
2001-01-09  13610.51  13732.85  13732.85  13460.82          0.0 -0.0185
2001-01-10  13432.65  13593.16  13593.16  13349.15          0.0 -0.0131
2001-01-11  13201.07  13433.09  13436.61  13123.81          0.0 -0.0172
2001-01-12  13347.74  13246.20  13451.95  13246.20          0.0  0.0111
...              ...       ...       ...       ...          ...     ...
2022-10-17  26775.79  26785.02  26814.92  26649.13  652800000.0 -0.0116
2022-10-18  27156.14  27167.73  27229.88  26910.10  660610000.0  0.0142
2022-10-19  27257.38  27225.17  27371.38  27192.79  575640000.0  0.0037
2022-10-20  27006.96  26981.75  27092.55  26872.45  603050000.0 -0.0092
2022-10-21  26890.58  26903.50  26985.38  26869.38  563050000.0 -0.0043

[5366 rows x 6 columns]

In [ ]:
jp_vaild = jp[jp['Volume']>0]

In [ ]:
jp_vaild

               Close      Open      High       Low       Volume  Change
Date
2011-07-01   9868.07   9883.00   9898.50   9853.50     111590.0  0.0053
2011-07-04   9965.09   9988.00  10003.50   9943.50     131380.0  0.0098
2011-07-05   9972.46   9973.00   9993.50   9948.50     132580.0  0.0007
2011-07-06  10082.48   9993.00  10083.50   9973.50     137710.0  0.0110
2011-07-07  10071.14  10048.00  10103.50  10028.50     133180.0 -0.0011
...              ...       ...       ...       ...          ...     ...
2022-10-17  26775.79  26785.02  26814.92  26649.13  652800000.0 -0.0116
2022-10-18  27156.14  27167.73  27229.88  26910.10  660610000.0  0.0142
2022-10-19  27257.38  27225.17  27371.38  27192.79  575640000.0  0.0037
2022-10-20  27006.96  26981.75  27092.55  26872.45  603050000.0 -0.0092
2022-10-21  26890.58  26903.50  26985.38  26869.38  563050000.0 -0.0043

[2766 rows x 6 columns]

In [ ]:
import os
import sys
import logging
import argparse
import json

import pandas as pd
import matplotlib.pyplot as plt
import FinanceDataReader as fdr

In [ ]:
BASE_DIR = "/content/drive/MyDrive/Colab Notebooks/project-rl"  ## 주소 알아서 바꾸기
ETF_LIST = ['KS11','KQ11','KS50', 'KS100', 'KRX100', 'KS200','DJI','IXIC', 'US500','RUTNU',\
                    'VIX', 'JP225','STOXX50', 'HK50', 'CSI300', 'TWII', 'HNX30', 'SSEC', 'UK100', 'DE30', 'FCHI'] 

'''
한국 주요 지수            미국 주요 지수                              국가별 대표 지수

심볼	설명                심볼	설명                                  심볼	설명
KS11	KOSPI 지수          DJI	다우존스 지수                           JP225	닛케이 225 선물
KQ11	KOSDAQ 지수         IXIC	나스닥 종합 지수                      STOXX50	유럽 STOXX 50
KS50	KOSPI 50 지수       US500	S&P 500 지수                          HK50	항셍 지수
KS100	KOSPI 100           RUTNU	러셀 2000 (US Small Cap 2000)         CSI300	CSI 300 (중국)
KRX100	KRX 100           VIX	CBOE 변동성 지수 (공포지수)             TWII	대만 가권 지수
KS200	코스피 200                                                      HNX30	베트남 하노이
                                                                      SSEC	상해 종합
                                                                      UK100	영국 FTSE
                                                                      DE30	독일 DAX 30
                                                                      FCHI	프랑스 CAC 40
'''


def making_csv(code) :
    if code not in ETF_LIST:
        print('ERROR : --code is not in ETF_LIST')
        exit(0)

    print(code)
    df = fdr.DataReader(code)
    df_valid = df[df['Volume']>0]
    df_valid.to_csv(os.path.join(BASE_DIR, 'data', 'etf') + f'{code}.csv')

    print('------------original etf data------------')
    print(df)
    print('------------delete volume ==0 -----------')
    print(df_valid)

def making_csv_all():
    for code in ETF_LIST:
        print(code)
        df = fdr.DataReader(code)
        df_valid = df[df['Volume']>0]
        df_valid.to_csv(os.path.join(BASE_DIR, 'data','etf',code)+'.csv')
        print('-'*50)
        print(df_valid)

In [ ]:
making_csv('US500')

US500
------------original etf data------------
              Close     Open     High      Low  Volume  Change
Date
1980-01-01   107.90   107.90   107.90   107.90     0.0  0.0000
1980-01-02   105.80   105.80   108.40   105.30     0.0 -0.0195
1980-01-03   105.20   105.20   106.10   103.30     0.0 -0.0057
1980-01-04   106.50   106.50   107.10   105.10     0.0  0.0124
1980-01-07   106.80   106.80   107.80   105.80     0.0  0.0028
...             ...      ...      ...      ...     ...     ...
2022-10-17  3677.95  3638.65  3689.73  3638.65     0.0  0.0265
2022-10-18  3719.98  3746.26  3762.79  3686.53     0.0  0.0114
2022-10-19  3695.16  3703.11  3728.58  3666.51     0.0 -0.0067
2022-10-20  3665.78  3689.05  3736.00  3656.44     0.0 -0.0080
2022-10-21  3752.75  3657.10  3757.89  3647.42     0.0  0.0237

[10798 rows x 6 columns]
------------delete volume ==0 -----------
Empty DataFrame
Columns: [Close, Open, High, Low, Volume, Change]
Index: []

In [ ]:
making_csv_all()

KS11
--------------------------------------------------
              Close     Open     High      Low        Volume  Change
Date
1981-05-01   123.60   123.60   123.60   123.60  3.330000e+06  0.0098
1981-05-02   123.50   123.50   123.50   123.50  2.040000e+06 -0.0008
1981-05-04   120.60   120.60   120.60   120.60  1.930000e+06 -0.0235
1981-05-06   120.70   120.70   120.70   120.70  1.690000e+06  0.0008
1981-05-07   119.30   119.30   119.30   119.30  1.480000e+06 -0.0116
...             ...      ...      ...      ...           ...     ...
2022-10-17  2219.71  2187.17  2221.05  2177.66  4.987800e+08  0.0032
2022-10-18  2249.95  2249.15  2251.74  2220.71  5.808900e+08  0.0136
2022-10-19  2237.44  2249.35  2266.80  2234.59  8.951600e+08 -0.0056
2022-10-20  2218.09  2225.53  2231.52  2200.44  1.110000e+09 -0.0086
2022-10-21  2213.12  2210.59  2224.04  2204.64  6.374900e+08 -0.0022

[11057 rows x 6 columns]
KQ11
--------------------------------------------------
             Close    Open    High     Low        Volume  Change
Date
2001-01-02  557.00  502.50  559.60  502.50  2.012100e+05  0.0593
2001-01-03  569.00  545.80  579.90  539.30  2.849900e+05  0.0215
2001-01-04  615.10  617.70  621.50  609.00  2.331300e+05  0.0810
2001-01-05  625.20  614.50  630.70  602.50  3.672300e+05  0.0164
2001-01-08  650.00  614.90  657.00  614.00  3.586200e+05  0.0397
...            ...     ...     ...     ...           ...     ...
2022-10-17  682.00  667.61  682.39  664.83  8.144200e+08  0.0055
2022-10-18  697.09  692.39  697.37  685.90  1.070000e+09  0.0221
2022-10-19  690.56  697.94  705.84  689.67  1.050000e+09 -0.0094
2022-10-20  680.44  688.44  693.14  675.89  1.050000e+09 -0.0147
2022-10-21  674.48  678.16  682.49  674.48  1.030000e+09 -0.0088

[5390 rows x 6 columns]
KS50
--------------------------------------------------
              Close     Open     High      Low      Volume  Change
Date
2011-11-07  1617.32  1629.33  1629.33  1612.42     50630.0 -0.0064
2011-11-08  1599.06  1622.78  1623.15  1596.07     50300.0 -0.0113
2011-11-09  1606.06  1619.19  1623.35  1598.06     56830.0  0.0044
2011-11-10  1518.35  1565.36  1567.21  1518.35     86820.0 -0.0546
2011-11-11  1566.95  1542.86  1567.73  1527.94     53200.0  0.0320
...             ...      ...      ...      ...         ...     ...
2022-10-17  1989.84  1964.94  1994.12  1959.77  55430000.0  0.0002
2022-10-18  2015.12  2015.04  2017.49  1989.69  53440000.0  0.0127
2022-10-19  1999.87  2012.67  2026.94  1997.98  51540000.0 -0.0076
2022-10-20  1977.25  1984.25  1986.77  1960.43  58610000.0 -0.0113
2022-10-21  1983.78  1971.19  1994.98  1971.19  40390000.0  0.0033

[2702 rows x 6 columns]
KS100
--------------------------------------------------
              Close     Open     High      Low      Volume  Change
Date
2011-11-04  1895.86  1876.38  1896.54  1870.23     90460.0  0.0340
2011-11-07  1883.69  1898.09  1898.09  1878.64     70380.0 -0.0064
2011-11-08  1864.19  1891.37  1891.66  1861.11     68170.0 -0.0104
2011-11-09  1871.18  1886.89  1891.46  1861.13     96060.0  0.0037
2011-11-10  1771.60  1824.69  1826.60  1771.60    120150.0 -0.0532
...             ...      ...      ...      ...         ...     ...
2022-10-17  2184.00  2156.49  2187.78  2150.52  80460000.0  0.0006
2022-10-18  2212.45  2211.45  2214.35  2184.24  80180000.0  0.0130
2022-10-19  2195.23  2211.06  2225.02  2193.22  76940000.0 -0.0078
2022-10-20  2174.32  2179.85  2184.24  2157.74  99020000.0 -0.0095
2022-10-21  2176.25  2167.35  2188.44  2166.67  69390000.0  0.0009

[2703 rows x 6 columns]
KRX100
--------------------------------------------------
              Close     Open     High      Low       Volume  Change
Date
2011-10-31  4065.93  4085.31  4135.22  4047.04      73540.0 -0.0097
2011-11-01  4064.16  4027.01  4101.32  4026.68      66100.0 -0.0004
2011-11-02  4033.74  3981.85  4038.30  3957.00      76570.0 -0.0075
2011-11-03  3969.43  4022.96  4022.96  3952.70      82000.0 -0.0159
2011-11-04  4103.12  4061.17  4105.07  4047.64      77920.0  0.0337
...             ...      ...      ...      ...          ...     ...
2022-10-17  4529.41  4470.48  4536.54  4457.59   87660000.0  0.0002
2022-10-18  4594.39  4589.66  4596.33  4532.96   88590000.0  0.0143
2022-10-19  4560.45  4590.39  4624.14  4552.52   83350000.0 -0.0074
2022-10-20  4511.97  4528.13  4536.22  4476.73  103370000.0 -0.0106
2022-10-21  4514.78  4497.34  4543.14  4494.23   73840000.0  0.0006

[2707 rows x 6 columns]
KS200
--------------------------------------------------
             Close    Open    High     Low       Volume  Change
Date
2000-12-26   63.35   64.11   64.19   63.04  141880000.0  0.0083
2001-01-02   65.41   63.33   65.47   62.97  130590000.0  0.0325
2001-01-03   65.38   64.28   65.79   63.99  182700000.0 -0.0005
2001-01-04   70.14   69.19   71.37   69.19  265500000.0  0.0728
2001-01-05   73.15   70.32   73.23   69.74  352410000.0  0.0429
...            ...     ...     ...     ...          ...     ...
2022-10-17  289.57  285.89  290.04  284.91  111600000.0  0.0007
2022-10-18  293.59  293.34  293.78  289.77  117120000.0  0.0139
2022-10-19  291.29  293.41  295.34  290.90  110850000.0 -0.0078
2022-10-20  288.61  289.33  290.07  286.50  136900000.0 -0.0092
2022-10-21  288.57  287.68  290.38  287.44  102370000.0 -0.0001

[5390 rows x 6 columns]
DJI
--------------------------------------------------
               Close      Open      High       Low       Volume  Change
Date
1988-01-04   2015.25   1938.83   2021.55   1938.83   20880000.0  0.0394
1988-01-05   2031.50   2015.25   2066.15   2015.25   27200000.0  0.0081
1988-01-06   2037.80   2031.33   2044.93   2022.05   18800000.0  0.0031
1988-01-07   2051.89   2037.96   2056.53   2011.60   21370000.0  0.0069
1988-01-08   1911.31   2052.10   2055.90   1908.70   27440000.0 -0.0685
...              ...       ...       ...       ...          ...     ...
2022-10-17  30188.79  30059.58  30310.55  29997.98  359310000.0  0.0184
2022-10-18  30527.49  30794.47  30836.88  30301.86  378980000.0  0.0112
2022-10-19  30425.26  30439.04  30660.88  30229.05  299060000.0 -0.0033
2022-10-20  30332.80  30411.92  30822.14  30265.22  323660000.0 -0.0030
2022-10-21  31083.02  30291.18  31119.27  30207.85  402890000.0  0.0247

[8772 rows x 6 columns]
IXIC
--------------------------------------------------
               Close      Open      High       Low        Volume  Change
Date
2006-06-15   2144.15   2098.37   2147.91   2086.00  1.610000e+09  0.0279
2006-06-16   2129.95   2140.51   2144.15   2122.78  1.990000e+09 -0.0066
2006-06-19   2110.42   2136.60   2138.77   2104.38  1.250000e+09 -0.0092
2006-06-20   2107.06   2110.92   2126.72   2103.77  1.250000e+09 -0.0016
2006-06-21   2141.20   2109.22   2152.56   2107.06  1.420000e+09  0.0162
...              ...       ...       ...       ...           ...     ...
2022-10-17  10675.80  10575.65  10696.59  10569.69  9.443100e+08  0.0343
2022-10-18  10772.40  10963.99  10972.97  10670.12  9.296200e+08  0.0090
2022-10-19  10680.51  10689.31  10808.04  10592.88  9.211300e+08 -0.0085
2022-10-20  10614.84  10657.41  10837.30  10574.55  8.662500e+08 -0.0061
2022-10-21  10859.72  10576.04  10875.72  10542.43  1.020000e+09  0.0231

[4118 rows x 6 columns]
US500
--------------------------------------------------
Empty DataFrame
Columns: [Close, Open, High, Low, Volume, Change]
Index: []
RUTNU
--------------------------------------------------
Empty DataFrame
Columns: [Close, Open, High, Low, Volume, Change]
Index: []
VIX
--------------------------------------------------
Empty DataFrame
Columns: [Close, Open, High, Low, Volume, Change]
Index: []
JP225
--------------------------------------------------
               Close      Open      High       Low       Volume  Change
Date
2011-07-01   9868.07   9883.00   9898.50   9853.50     111590.0  0.0053
2011-07-04   9965.09   9988.00  10003.50   9943.50     131380.0  0.0098
2011-07-05   9972.46   9973.00   9993.50   9948.50     132580.0  0.0007
2011-07-06  10082.48   9993.00  10083.50   9973.50     137710.0  0.0110
2011-07-07  10071.14  10048.00  10103.50  10028.50     133180.0 -0.0011
...              ...       ...       ...       ...          ...     ...
2022-10-17  26775.79  26785.02  26814.92  26649.13  652800000.0 -0.0116
2022-10-18  27156.14  27167.73  27229.88  26910.10  660610000.0  0.0142
2022-10-19  27257.38  27225.17  27371.38  27192.79  575640000.0  0.0037
2022-10-20  27006.96  26981.75  27092.55  26872.45  603050000.0 -0.0092
2022-10-21  26890.58  26903.50  26985.38  26869.38  563050000.0 -0.0043

[2766 rows x 6 columns]
STOXX50
--------------------------------------------------
              Close     Open     High      Low       Volume  Change
Date
2011-08-15  2324.48  2320.62  2339.92  2306.24   32520000.0 -0.1697
2011-08-16  2323.67  2309.57  2323.67  2269.99  102980000.0 -0.0003
2011-08-17  2331.12  2313.37  2355.67  2281.88   88840000.0  0.0032
2011-08-18  2206.61  2313.16  2313.16  2177.29  130880000.0 -0.0534
2011-08-19  2159.07  2203.18  2203.18  2117.68  158300000.0 -0.0215
...             ...      ...      ...      ...          ...     ...
2022-10-17  3441.64  3382.12  3456.81  3369.55   26490000.0  0.0177
2022-10-18  3463.83  3449.95  3511.06  3449.95   32670000.0  0.0064
2022-10-19  3471.24  3466.71  3498.20  3458.17   23230000.0  0.0021
2022-10-20  3492.85  3467.57  3501.58  3451.75   29620000.0  0.0062
2022-10-21  3476.63  3477.27  3488.01  3422.93   38820000.0 -0.0046

[2865 rows x 6 columns]
HK50
--------------------------------------------------
               Close      Open      High       Low        Volume  Change
Date
2008-02-18  23759.25  24344.27  24413.89  23735.87  1.670000e+09 -0.0161
2010-07-28  21091.18  20961.55  21199.55  20902.16  1.350000e+09  0.0056
2010-07-29  21093.82  21091.17  21130.74  20970.93  1.010000e+09  0.0001
2011-08-12  19620.01  19955.82  19955.82  19575.00  2.160000e+09  0.0013
2011-08-15  20260.10  20056.78  20264.33  19924.56  1.830000e+09  0.0326
...              ...       ...       ...       ...           ...     ...
2022-10-17  16612.90  16479.74  16754.52  16308.95  2.060000e+09  0.0015
2022-10-18  16914.58  16860.20  16914.58  16558.41  1.970000e+09  0.0182
2022-10-19  16511.28  16805.91  16923.12  16508.37  1.710000e+09 -0.0238
2022-10-20  16280.22  16230.79  16452.97  16010.72  2.300000e+09 -0.0140
2022-10-21  16211.12  16331.11  16359.04  16137.18  2.050000e+09 -0.0042

[2756 rows x 6 columns]
CSI300
--------------------------------------------------
              Close     Open     High      Low    Volume  Change
Date
2005-01-04   982.79   994.77   994.77   980.66    7410.0 -0.0172
2005-01-05   992.56   981.58   997.32   979.88    7120.0  0.0099
2005-01-06   983.17   993.33   993.79   980.33    6290.0 -0.0095
2005-01-07   983.96   983.05   995.71   979.81    7300.0  0.0008
2005-01-10   993.88   983.76   993.96   979.79    5790.0  0.0101
...             ...      ...      ...      ...       ...     ...
2022-10-17  3846.41  3822.24  3849.62  3809.12  104190.0  0.0010
2022-10-18  3838.27  3865.83  3870.22  3831.17   88350.0 -0.0021
2022-10-19  3776.53  3827.47  3840.49  3776.53   81580.0 -0.0161
2022-10-20  3754.93  3746.58  3804.25  3726.79   90290.0 -0.0057
2022-10-21  3742.89  3753.89  3768.69  3724.69   98750.0 -0.0032

[4327 rows x 6 columns]
TWII
--------------------------------------------------
               Close      Open      High       Low        Volume  Change
Date
2011-03-17   8282.69   8190.50   8282.69   8150.73  3.050000e+06 -0.0050
2011-03-18   8394.75   8343.79   8399.17   8312.88  3.090000e+06  0.0135
2011-03-21   8467.71   8421.66   8508.20   8394.22  2.460000e+06  0.0087
2011-03-22   8508.04   8523.27   8552.82   8508.04  2.780000e+06  0.0048
2011-03-23   8545.08   8529.93   8551.12   8481.96  2.470000e+06  0.0044
...              ...       ...       ...       ...           ...     ...
2022-10-17  12966.05  12988.83  12988.83  12814.82  3.040000e+09 -0.0123
2022-10-18  13124.68  13075.05  13143.15  12978.13  2.610000e+09  0.0122
2022-10-19  12976.76  13096.35  13155.62  12976.76  2.470000e+09 -0.0113
2022-10-20  12946.10  12912.93  12946.10  12698.91  3.530000e+09 -0.0024
2022-10-21  12819.20  12931.20  12954.02  12813.60  2.220000e+09 -0.0098

[2859 rows x 6 columns]
HNX30
--------------------------------------------------
             Close    Open    High     Low   Volume  Change
Date
2014-11-04  176.98  177.44  178.46  176.04  28890.0 -0.0026
2014-11-05  177.22  176.98  177.78  174.24  43150.0  0.0014
2014-11-06  179.64  177.24  179.94  177.16  37250.0  0.0137
2014-11-07  180.13  179.64  180.46  178.78  23960.0  0.0027
2014-11-10  180.62  177.55  182.22  177.55  44590.0  0.0027
...            ...     ...     ...     ...      ...     ...
2022-10-17  381.73  384.75  384.75  375.11  30410.0 -0.0078
2022-10-18  388.36  380.06  395.11  380.03  37750.0  0.0174
2022-10-19  386.33  388.48  392.94  385.02  24060.0 -0.0052
2022-10-20  382.18  386.33  388.04  379.39  21670.0 -0.0107
2022-10-21  360.92  381.76  382.61  359.11  60910.0 -0.0556

[1991 rows x 6 columns]
SSEC
--------------------------------------------------
              Close     Open     High      Low        Volume  Change
Date
1994-11-25   685.33   690.04   694.97   684.09  6.033000e+07  0.0108
1994-11-28   681.49   683.83   683.83   677.97  2.303000e+07 -0.0056
1994-11-29   687.55   671.70   687.57   671.04  3.159000e+07  0.0089
1994-11-30   683.59   687.03   689.96   682.81  3.510000e+07 -0.0058
1994-12-01   682.30   683.38   684.72   679.99  2.085000e+07 -0.0019
...             ...      ...      ...      ...           ...     ...
2022-10-17  3084.94  3060.52  3087.19  3052.71  2.626000e+10  0.0042
2022-10-18  3080.96  3094.93  3099.92  3074.22  2.456000e+10 -0.0013
2022-10-19  3044.38  3073.26  3081.39  3044.38  2.309000e+10 -0.0119
2022-10-20  3035.05  3029.30  3070.26  3013.69  2.447000e+10 -0.0031
2022-10-21  3038.93  3038.04  3055.42  3026.96  2.453000e+10  0.0013

[6768 rows x 6 columns]
UK100
--------------------------------------------------
              Close     Open     High      Low        Volume  Change
Date
2011-08-12  5320.03  5162.83  5320.03  5099.31  1.020000e+09  0.0294
2011-08-15  5350.58  5320.03  5377.23  5319.38  6.956400e+08  0.0057
2011-08-16  5357.63  5350.58  5362.15  5265.83  7.163800e+08  0.0013
2011-08-17  5331.60  5357.63  5371.08  5279.93  6.719400e+08 -0.0049
2011-08-18  5092.23  5331.60  5331.60  5041.59  1.180000e+09 -0.0449
...             ...      ...      ...      ...           ...     ...
2022-10-17  6920.24  6858.79  6959.71  6850.43  9.510200e+08  0.0090
2022-10-18  6936.74  6920.24  7017.40  6920.24  7.984600e+08  0.0024
2022-10-19  6924.99  6936.74  6968.33  6890.66  6.995200e+08 -0.0017
2022-10-20  6943.91  6924.99  6954.21  6894.85  8.127400e+08  0.0027
2022-10-21  6969.73  6943.91  6976.19  6864.13  6.683900e+08  0.0037

[2829 rows x 6 columns]
DE30
--------------------------------------------------
               Close      Open      High       Low       Volume  Change
Date
2001-09-11   4273.53   4680.80   4788.38   4130.52  119870000.0 -0.0849
2008-02-18   6967.55   6865.57   6997.77   6865.57  114680000.0  0.0198
2009-02-16   4366.64   4386.46   4421.78   4359.29   86110000.0 -0.0106
2010-05-17   6066.92   6029.91   6151.54   6026.32  144990000.0  0.0017
2010-05-18   6155.93   6144.08   6181.26   6113.87  122110000.0  0.0147
...              ...       ...       ...       ...          ...     ...
2022-10-17  12649.03  12467.54  12716.81  12398.05   57200000.0  0.0170
2022-10-18  12765.61  12788.53  12931.76  12746.36   65990000.0  0.0092
2022-10-19  12741.41  12817.63  12819.11  12705.26   63630000.0 -0.0019
2022-10-20  12767.41  12685.16  12818.34  12628.78   52820000.0  0.0020
2022-10-21  12730.90  12641.12  12775.52  12548.15   82220000.0 -0.0029

[3161 rows x 6 columns]
FCHI
--------------------------------------------------
              Close     Open     High      Low      Volume  Change
Date
1998-01-02  3040.14  3012.01  3048.00  3005.84   6750000.0  0.0137
1998-01-05  3072.84  3023.43  3075.30  3023.43  16130000.0  0.0108
1998-01-06  3037.73  3055.10  3055.10  3025.22  16010000.0 -0.0114
1998-01-07  3006.73  3012.80  3062.21  3006.73  24810000.0 -0.0102
1998-01-08  2954.94  3034.96  3035.98  2949.70  22690000.0 -0.0172
...             ...      ...      ...      ...         ...     ...
2022-10-17  6040.66  5949.65  6068.37  5910.39  63830000.0  0.0183
2022-10-18  6067.00  6098.60  6139.78  6057.38  66540000.0  0.0044
2022-10-19  6040.72  6092.77  6109.97  6040.72  66380000.0 -0.0043
2022-10-20  6086.90  6046.81  6103.50  6029.53  62630000.0  0.0076
2022-10-21  6035.39  6021.58  6056.04  5952.88  72700000.0 -0.0085

[6338 rows x 6 columns]